version: '3'

services:
  # Database
  database:
    image: postgres:9.6
    restart: always
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./pg_backups:/pg_backups
      - ./database_subset:/data
    networks:
       - survey

  #Backend Django
  backend:
    # user: 1000:1000
    build: ./backend
    image: survey_progress_backend    
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./log:/log
      - ./archive:/archive
#    depends_on:
#      - database
    networks:
       - survey

  # Frontend
  frontend:
    # User id do ambiente de testing
    user: 1000:1000
    build: ./frontend
    image: survey_progress_frontend
    volumes:
      - ./frontend:/app/
    env_file:
      - .env
    networks:
       - survey

  iipserver:
    build: ./iipimage
    volumes:
      - ./tiff:/images
      - ./iipimage/start_fcgi.sh:/iipsrv/start_fcgi.sh
    environment:
      - LOGFILE=/tmp/iipsrv.log
      - VERBOSITY=10
      - FILESYSTEM_PREFIX=/images/
      - MAX_IMAGE_CACHE_SIZE=10
      - MAX_CVT=3000
      - JPEG_QUALITY=90
      - CORS=*
    command: sh start_fcgi.sh
    networks:
       - survey

  nginx:
    image: nginx:latest
    ports:
      - 7001:8080
    volumes:
      - ./frontend/build:/var/www/frontend
      - ./nginx/conf.d:/etc/nginx/conf.d/default.conf:ro
      - ./log:/log
    depends_on:
      - backend
      - frontend
    networks:
       - survey

networks:
  survey:
