# Generated by Django 2.1.1 on 2018-09-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfw_attempt_id', models.BigIntegerField(help_text='Unique identifier for each image (1 image is composed by 62 CCDs)', verbose_name='Image Id')),
                ('nite', models.DateField(help_text='Night at which the observation was made.', verbose_name='Night')),
                ('expnum', models.BigIntegerField(help_text='Unique identifier for each image, same function as pfw_attenp_id (it also recorded in the file name)', verbose_name='Exposure')),
                ('ccdnum', models.IntegerField(help_text='CCD Number (1, 2, ..., 62)', verbose_name='CCD')),
                ('band', models.CharField(choices=[('u', 'u'), ('g', 'g'), ('r', 'r'), ('i', 'i'), ('z', 'z'), ('Y', 'Y')], help_text='Filter used to do the observation (u, g, r, i, z, Y).', max_length=1, verbose_name='Filter')),
                ('exptime', models.FloatField(help_text='Exposure time of observation.', verbose_name='Exposure time')),
                ('crossra0', models.BooleanField(default=False, verbose_name='Cross RA 0')),
                ('racmin', models.FloatField(help_text='Minimal and maximum right ascension respectively of the CCD cover.', verbose_name='racmin')),
                ('racmax', models.FloatField(help_text='Minimal and maximum right ascension respectively of the CCD cover.', verbose_name='racmax')),
                ('deccmin', models.FloatField(help_text='Minimum and maximum declination respectively of the CCD cover.', verbose_name='deccmin')),
                ('deccmax', models.FloatField(help_text='Minimum and maximum declination respectively of the CCD cover.', verbose_name='deccmax')),
                ('ra_cent', models.FloatField(help_text='Right ascension of the CCD center', verbose_name='ra_cent')),
                ('dec_cent', models.FloatField(help_text='Declination of the CCD center', verbose_name='dec_cent')),
                ('rac1', models.FloatField(help_text='CCD Corner Coordinates 1 - upper left.', verbose_name='rac1')),
                ('rac2', models.FloatField(help_text='CCD Corner Coordinates 2 - lower left.', verbose_name='rac2')),
                ('rac3', models.FloatField(help_text='CCD Corner Coordinates 3 - lower right.', verbose_name='rac3')),
                ('rac4', models.FloatField(help_text='CCD Corner Coordinates 4 - upper right).', verbose_name='rac4')),
                ('decc1', models.FloatField(help_text='CCD Corner Coordinates 1 - upper left.', verbose_name='decc1')),
                ('decc2', models.FloatField(help_text='CCD Corner Coordinates 2 - lower left.', verbose_name='decc2')),
                ('decc3', models.FloatField(help_text='CCD Corner Coordinates 3 - lower right.', verbose_name='decc3')),
                ('decc4', models.FloatField(help_text='CCD Corner Coordinates 4 - upper right).', verbose_name='decc4')),
                ('path', models.TextField(help_text='Path in the DES database where the image is stored.', verbose_name='Path')),
                ('filename', models.CharField(help_text='Name of FITS file with a CCD image.', max_length=256, verbose_name='Filename')),
                ('downloaded', models.BooleanField(default=False, help_text='flag indicating whether the image was downloaded from DES.', verbose_name='Downloaded')),
            ],
        ),
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obs', models.CharField(blank=True, help_text='Date and time of observation', max_length=256, null=True, verbose_name='Observation Date')),
                ('nite', models.DateField(blank=True, help_text='Night at which the observation was made.', null=True, verbose_name='Night')),
                ('expnum', models.BigIntegerField(blank=True, help_text='Unique identifier for each image, same function as pfw_attenp_id (it also recorded in the file name)', null=True, verbose_name='Exposure')),
                ('band', models.CharField(choices=[('u', 'u'), ('g', 'g'), ('r', 'r'), ('i', 'i'), ('z', 'z'), ('Y', 'Y')], help_text='Filter used to do the observation (u, g, r, i, z, Y).', max_length=1, verbose_name='Filter')),
                ('radeg', models.FloatField(blank=True, null=True, verbose_name='RA')),
                ('decdeg', models.FloatField(blank=True, null=True, verbose_name='DEC')),
                ('filename', models.CharField(blank=True, help_text='Name of FITS file with a CCD image.', max_length=256, null=True, verbose_name='Filename')),
                ('filetype', models.CharField(blank=True, max_length=256, null=True, verbose_name='Filetype')),
                ('exptime', models.FloatField(blank=True, help_text='Exposure time of observation.', null=True, verbose_name='Exposure time')),
                ('airmass', models.FloatField(blank=True, null=True, verbose_name='Airmass')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='Humidity')),
                ('pressure', models.FloatField(blank=True, null=True, verbose_name='Pressure')),
            ],
        ),
        migrations.AddIndex(
            model_name='exposure',
            index=models.Index(fields=['expnum'], name='survey_expo_expnum_560830_idx'),
        ),
        migrations.AddIndex(
            model_name='exposure',
            index=models.Index(fields=['expnum', 'band'], name='survey_expo_expnum_4fed98_idx'),
        ),
        migrations.AddIndex(
            model_name='exposure',
            index=models.Index(fields=['nite'], name='survey_expo_nite_cc544e_idx'),
        ),
        migrations.AddIndex(
            model_name='exposure',
            index=models.Index(fields=['radeg'], name='survey_expo_radeg_4b6523_idx'),
        ),
        migrations.AddIndex(
            model_name='exposure',
            index=models.Index(fields=['decdeg'], name='survey_expo_decdeg_003268_idx'),
        ),
        migrations.AddIndex(
            model_name='ccd',
            index=models.Index(fields=['expnum'], name='survey_ccd_expnum_9e0a29_idx'),
        ),
        migrations.AddIndex(
            model_name='ccd',
            index=models.Index(fields=['expnum', 'ccdnum'], name='survey_ccd_expnum_be3638_idx'),
        ),
        migrations.AddIndex(
            model_name='ccd',
            index=models.Index(fields=['expnum', 'ccdnum', 'band'], name='survey_ccd_expnum_b60a42_idx'),
        ),
        migrations.AddIndex(
            model_name='ccd',
            index=models.Index(fields=['nite'], name='survey_ccd_nite_6434c2_idx'),
        ),
        migrations.AddIndex(
            model_name='ccd',
            index=models.Index(fields=['rac1'], name='survey_ccd_rac1_4faf8d_idx'),
        ),
        migrations.AddIndex(
            model_name='ccd',
            index=models.Index(fields=['rac2'], name='survey_ccd_rac2_b75105_idx'),
        ),
        migrations.AddIndex(
            model_name='ccd',
            index=models.Index(fields=['rac3'], name='survey_ccd_rac3_7523ef_idx'),
        ),
        migrations.AddIndex(
            model_name='ccd',
            index=models.Index(fields=['rac4'], name='survey_ccd_rac4_9c9e51_idx'),
        ),
        migrations.AddIndex(
            model_name='ccd',
            index=models.Index(fields=['decc1'], name='survey_ccd_decc1_07bd27_idx'),
        ),
        migrations.AddIndex(
            model_name='ccd',
            index=models.Index(fields=['decc2'], name='survey_ccd_decc2_1592bd_idx'),
        ),
        migrations.AddIndex(
            model_name='ccd',
            index=models.Index(fields=['decc3'], name='survey_ccd_decc3_17419a_idx'),
        ),
        migrations.AddIndex(
            model_name='ccd',
            index=models.Index(fields=['decc4'], name='survey_ccd_decc4_09f8c7_idx'),
        ),
    ]
